//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFileList.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomOpenProcess {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomOpenProcess"]));
            }
            set {
                this["CustomOpenProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUpgreated {
            get {
                return ((bool)(this["IsUpgreated"]));
            }
            set {
                this["IsUpgreated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsExcludeHiddenDirectory {
            get {
                return ((bool)(this["IsExcludeHiddenDirectory"]));
            }
            set {
                this["IsExcludeHiddenDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsExcludeSystemDirectory {
            get {
                return ((bool)(this["IsExcludeSystemDirectory"]));
            }
            set {
                this["IsExcludeSystemDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsExcludeDotStartDirectory {
            get {
                return ((bool)(this["IsExcludeDotStartDirectory"]));
            }
            set {
                this["IsExcludeDotStartDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsExcludeHiddenFile {
            get {
                return ((bool)(this["IsExcludeHiddenFile"]));
            }
            set {
                this["IsExcludeHiddenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsExcludeSystemFile {
            get {
                return ((bool)(this["IsExcludeSystemFile"]));
            }
            set {
                this["IsExcludeSystemFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsExcludeDotStartFile {
            get {
                return ((bool)(this["IsExcludeDotStartFile"]));
            }
            set {
                this["IsExcludeDotStartFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsIgnoreGettingLastSaveTime {
            get {
                return ((bool)(this["IsIgnoreGettingLastSaveTime"]));
            }
            set {
                this["IsIgnoreGettingLastSaveTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int WindowScaleTransformPer {
            get {
                return ((int)(this["WindowScaleTransformPer"]));
            }
            set {
                this["WindowScaleTransformPer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ExcludeExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcludeExtensions"]));
            }
            set {
                this["ExcludeExtensions"] = value;
            }
        }
    }
}
